name: build

on:
  push:
    branches: [ master ]
    tags:
      - '*'
  pull_request:

jobs:

  build_osx:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: '5.16.2'
    - name: Perl version
      run: perl -v
    - name: Install dependencies
      run: brew install squashfs
    - name: run build
      run: make build
    - name: Test created binary on sample file
      env:
        GITHUB_CREDENTIALS: "metanorma-ci:${{ secrets.METANORMA_CI_PAT_TOKEN }}"
      run: |
        make test
    - uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: samples_macos_logs
        path: test_*.log
    - uses: actions/upload-artifact@v2
      with:
        name: samples
        path: build/**/published/*
    - name: Copy release binary
      run: cp build/metanorma metanorma-darwin-x64
    - name: Set release binary permissions
      run: chmod a+x metanorma-darwin-x64
    - name: Release binary
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: metanorma-darwin-x64
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_linux:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: '5.16.2'
    - name: Perl version
      run: perl -v
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get -y -q install squashfs-tools bison flex texinfo
    - name: Check clang
      run: clang -v
    - name: Check clang++
      run: clang++ -v
    - name: Use Clang for compilation
      run: sudo update-alternatives --install /usr/bin/cc cc /usr/bin/clang 100 && sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++ 100
    - name: Enable swap
      run: sudo fallocate -l 8g /mnt/compile.swap && sudo chmod 600 /mnt/compile.swap && sudo mkswap /mnt/compile.swap && sudo swapon /mnt/compile.swap
    - name: Check swap
      run: sudo swapon --all --verbose
    - name: run build
      timeout-minutes: 180
      # # https://trac.sagemath.org/ticket/19762
      env:
        CC: /usr/bin/clang
        CXX: /usr/bin/clang++
      run: make build
    - name: Test created binary on sample file
      env:
        GITHUB_CREDENTIALS: "metanorma-ci:${{ secrets.METANORMA_CI_PAT_TOKEN }}"
      run: |
        make test
    - uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: samples_linux_logs
        path: test_*.log
    - uses: actions/upload-artifact@v2
      with:
        name: samples
        path: build/**/published/*
    - name: Copy release binary
      run: mv build/metanorma metanorma-linux-x64
    - name: Set release binary permissions
      run: chmod a+x metanorma-linux-x64
    - name: Release binary
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: metanorma-linux-x64
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
       ruby-version: '2.6'
    - name: gem version
      run: gem -v
    - name: Check swap
      run: systeminfo
    - name: Install tools
      uses: nick-invision/retry@v1
      with:
        polling_interval_seconds: 5
        timeout_minutes: 5
        max_attempts: 3
        command: choco install --no-progress yq make gnuwin32-coreutils.install gzip wget git
    - name: Bundle install
      run: bundle install
    - name: Run build
      shell: cmd
      run: make -f Makefile.win build SHELL=cmd
    - name: Test created binary on sample file
      env:
        GITHUB_CREDENTIALS: "metanorma-ci:${{ secrets.METANORMA_CI_PAT_TOKEN }}"
      shell: cmd
      run: |
        :: for some reason mparallel doesn't work on GitHub Actions
        :: make -f Makefile.win test SHELL=cmd
        make -f Makefile.win test-flavor SHELL=cmd TEST_FLAVOR=iso
        make -f Makefile.win test-flavor SHELL=cmd TEST_FLAVOR=cc
        make -f Makefile.win test-flavor SHELL=cmd TEST_FLAVOR=gb
        make -f Makefile.win test-flavor SHELL=cmd TEST_FLAVOR=iec
        make -f Makefile.win test-flavor SHELL=cmd TEST_FLAVOR=itu
        make -f Makefile.win test-flavor SHELL=cmd TEST_FLAVOR=ogc
        make -f Makefile.win test-flavor SHELL=cmd TEST_FLAVOR=un
        make -f Makefile.win test-flavor SHELL=cmd TEST_FLAVOR=iho
        make -f Makefile.win test-flavor SHELL=cmd TEST_FLAVOR=nist
    - name: Copy release binary
      run: cp build/metanorma.exe metanorma-windows-x64.exe
    - name: Release binary
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: metanorma-windows-x64.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
