name: compile_windows

# Removed pull request trigger - causes to 2 heavy simultaneously jobs to execute
on: [push]

jobs:
  build_windows:
    runs-on: windows-2016
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.4'
    # By Default github action windows env does not set up build tools, call VsDevCmd build tools
    - name: Prepare build tools
      run: "C:\\Program Files \\(x86\\)\\Microsoft Visual Studio\\2017\\Enterprise\\Common7\\Tools\\VsDevCmd.bat"
    - name: Run build
      run: PowerShell.exe bin\build.ps1
    # - name: Install dependencies
    #   run: brew install squashfs
    # - name: Download and install rubyc
    #   run: curl -L http://enclose.io/rubyc/rubyc-darwin-x64.gz | gunzip > rubyc && chmod +x rubyc
    # - name: run build
    #   run: make build
    # - name: Test created binary on sample file
    #   run: ./build/metanorma --type iso -x html ./sources/iso/iso-rice-en.adoc
    # - name: Copy release binary
    #   run: cp build/metanorma metanorma-darwin-x64
    # - name: Set release binary permissions
    #   run: chmod a+x metanorma-darwin-x64
    # - name: Release binary
    #   uses: softprops/action-gh-release@v1
    #   if: startsWith(github.ref, 'refs/tags/')
    #   with:
    #     files: metanorma-darwin-x64
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
